version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: recoverer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongo:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: recoverer-backend
    restart: unless-stopped
    environment:
      - PROJECT_NAME=wallet-recoverer
      - API_BASE=/api
      - MONGO_URI=mongodb://recoverer-mongo:27017/wallet_recoverer_db
      - MONGO_DB_NAME=wallet_recoverer_db
      - JWT_SECRET=changeme_fill_in_step_later
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: recoverer-frontend
    restart: unless-stopped
    environment:
      - PROJECT_NAME=wallet-recoverer
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - NEXT_PUBLIC_PARALLAX=1
    depends_on:
      - backend
    ports:
      - "3000:3000"

networks:
  default:
    name: recoverynet
