services:
  mongo:
    image: mongo:6.0
    container_name: ${MONGO_SERVICE_NAME}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./.data/mongo:/data/db
    command: ["--bind_ip_all"]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ${BACKEND_SERVICE_NAME}
    restart: unless-stopped
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - API_BASE=${API_BASE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    depends_on:
      - mongo

networks:
  default:
    name: ${NETWORK_NAME}
