version: '3.9'

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "${MDB_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - MDB_URI=${MDB_URI}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    ports:
      - "${BE_PORT:-8000}:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "${FE_PORT:-3000}:3000"
    command: npm run dev

volumes:
  mongo_data:
    driver: local

